@echo off
if "%~1" == "" (
    echo use: %0 version_file_name
    goto :eof
)

if not exist "%~1" (
    echo file '%~1' not exist
    goto :eof
)

setlocal

set FILE_NAME=%~1

rem Определяем начальные значения
set VERSION_MAJOR=0
set VERSION_MINOR=0
set VERSION_BUILD_ID=0
set VERSION_BUILD_DATE=%date:~6,4%-%date:~3,2%-%date:~0,2% %time:~0,2%:%time:~3,2%:%time:~6,2%

rem Парсим файл на предмет билда
for /f "tokens=1,2,* usebackq delims= " %%i in ("%FILE_NAME%") do call :parse %%i %%j %%k

echo Version %VERSION_MAJOR%.%VERSION_MINOR%.%VERSION_BUILD_ID%
rem Создаем новый файл
echo //Autogenerated version file > "%FILE_NAME%"
echo #define VERSION_MAJOR %VERSION_MAJOR% >> "%FILE_NAME%"
echo #define VERSION_MINOR %VERSION_MINOR% >> "%FILE_NAME%"
echo #define VERSION_BUILD_ID %VERSION_BUILD_ID% >> "%FILE_NAME%"
echo #define VERSION_STR_MAJOR "%VERSION_MAJOR%" >> "%FILE_NAME%"
echo #define VERSION_STR_MINOR "%VERSION_MINOR%" >> "%FILE_NAME%"
echo #define VERSION_STR_BUILD_ID "%VERSION_BUILD_ID%" >> "%FILE_NAME%"
echo #define VERSION_STR_FULL "%VERSION_MAJOR%.%VERSION_MINOR%.%VERSION_BUILD_ID%" >> "%FILE_NAME%"
echo #define VERSION_STR_BUILD_DATE "%VERSION_BUILD_DATE%" >> "%FILE_NAME%"
echo #define VERSION_STR_DESC "v%VERSION_MAJOR%.%VERSION_MINOR%.%VERSION_BUILD_ID% (%VERSION_BUILD_DATE%)" >> "%FILE_NAME%"

rem pause
goto :eof


:parse
    if not "%1" == "#define" goto :eof
    if "%~3" == "" goto :eof
    if "%2" == "VERSION_MAJOR" (
        set VERSION_MAJOR=%~3
        goto :eof
    )
    if "%2" == "VERSION_MINOR" (
        set VERSION_MINOR=%~3
        goto :eof
    )
    if "%2" == "VERSION_BUILD_ID" (
        set /a VERSION_BUILD_ID=%~3+1
        goto :eof
    )
goto :eof
