# Константы названий
name_alien=Ален
name_xflow=Иксфлоу
name_chrome=Хром
name_slamin=Салюмин

component_group_name_spoiler=       Спойлер
component_group_name_hood=          Капот
component_group_name_roof=          Крыша
component_group_name_sideskirt=     Крылья #Обтекатель, Wings
component_group_name_lamps=         Фары
component_group_name_nitro=         Азот
component_group_name_exhaust=       Выхлопная
component_group_name_wheels=        Колеса
component_group_name_stereo=        Стерео
component_group_name_hydraulics=    Гидравлика
component_group_name_front_bumper=  БамперП
component_group_name_rear_bumper=   БамперЗ
component_group_name_vents=         Вентиляция
component_group_name_bullbars=      Кингурятник
component_group_name_front_bullbars=КингурятникП
component_group_name_rear_bullbars= КингурятникЗ

# Описание компонент тюнингра
#                  название_модели;слот;цена;    ид;  название группы;                название внутригруппы
vehicle_component_defs=spl_b_mar_m; 0;  400;    1000;$(component_group_name_spoiler);Про
vehicle_component_defs=spl_b_bab_m; 0;  550;    1001;$(component_group_name_spoiler);Победа
vehicle_component_defs=spl_b_bar_m; 0;  200;    1002;$(component_group_name_spoiler);Драг
vehicle_component_defs=spl_b_mab_m; 0;  250;    1003;$(component_group_name_spoiler);Альфа
vehicle_component_defs=spl_b_bar_l; 0;  400;    1014;$(component_group_name_spoiler);Чемпион
vehicle_component_defs=spl_b_bbr_l; 0;  500;    1015;$(component_group_name_spoiler);Гонка
vehicle_component_defs=spl_b_bbr_m; 0;  200;    1016;$(component_group_name_spoiler);Воркс
vehicle_component_defs=spl_b_bbb_m; 0;  350;    1023;$(component_group_name_spoiler);Ярость
vehicle_component_defs=spl_a_f_r;   0;  810;    1049;$(component_group_name_spoiler);$(name_alien)  # Flash
vehicle_component_defs=spl_c_f_r;   0;  620;    1050;$(component_group_name_spoiler);$(name_xflow)  # Flash
vehicle_component_defs=spl_a_st_r;  0;  620;    1058;$(component_group_name_spoiler);$(name_alien)  # Statum
vehicle_component_defs=spl_c_st_r;  0;  530;    1060;$(component_group_name_spoiler);$(name_xflow)  # Statum
vehicle_component_defs=spl_a_s_b;   0;  580;    1138;$(component_group_name_spoiler);$(name_alien)  # Sultan
vehicle_component_defs=spl_c_s_b;   0;  470;    1139;$(component_group_name_spoiler);$(name_xflow)  # Sultan
vehicle_component_defs=spl_c_l_b;   0;  490;    1146;$(component_group_name_spoiler);$(name_xflow)  # Elegy
vehicle_component_defs=spl_a_l_b;   0;  600;    1147;$(component_group_name_spoiler);$(name_alien)  # Elegy
vehicle_component_defs=spl_c_j_b;   0;  550;    1158;$(component_group_name_spoiler);$(name_xflow)  # Jester
vehicle_component_defs=spl_a_j_b;   0;  650;    1162;$(component_group_name_spoiler);$(name_alien)  # Jester
vehicle_component_defs=spl_c_u_b;   0;  450;    1163;$(component_group_name_spoiler);$(name_xflow)  # Uranus
vehicle_component_defs=spl_a_u_b;   0;  550;    1164;$(component_group_name_spoiler);$(name_alien)  # Uranus

vehicle_component_defs=bnt_b_sc_m;  1;  100;    1004;$(component_group_name_hood);Чемпион
vehicle_component_defs=bnt_b_sc_l;  1;  150;    1005;$(component_group_name_hood);Ярость
vehicle_component_defs=bnt_b_sc_p_m;1;  220;    1011;$(component_group_name_hood);Гонка
vehicle_component_defs=bnt_b_sc_p_l;1;  250;    1012;$(component_group_name_hood);Воркс
vehicle_component_defs=bnt_lr_slv1; 1;  100;    1111;$(component_group_name_hood);Знак1             # Slamvan
vehicle_component_defs=bnt_lr_slv2; 1;  100;    1112;$(component_group_name_hood);Знак2             # Slamvan

vehicle_component_defs=rf_b_sc_r;   2;  80;     1006;$(component_group_name_roof);Воздухозаборник
vehicle_component_defs=rf_a_s;      2;  170;    1032;$(component_group_name_roof);$(name_alien)     # Sultan
vehicle_component_defs=rf_c_s;      2;  120;    1033;$(component_group_name_roof);$(name_xflow)     # Sultan
vehicle_component_defs=rf_c_l;      2;  150;    1035;$(component_group_name_roof);$(name_xflow)     # Elegy
vehicle_component_defs=rf_a_l;      2;  190;    1038;$(component_group_name_roof);$(name_alien)     # Elegy
vehicle_component_defs=rf_c_f;      2;  130;    1053;$(component_group_name_roof);$(name_xflow)     # Flash
vehicle_component_defs=rf_a_f;      2;  210;    1054;$(component_group_name_roof);$(name_alien)     # Flash
vehicle_component_defs=rf_a_st;     2;  230;    1055;$(component_group_name_roof);$(name_alien)     # Statum
vehicle_component_defs=rf_c_st;     2;  180;    1061;$(component_group_name_roof);$(name_xflow)     # Statum
vehicle_component_defs=rf_a_j;      2;  250;    1067;$(component_group_name_roof);$(name_alien)     # Jester
vehicle_component_defs=rf_c_j;      2;  200;    1068;$(component_group_name_roof);$(name_xflow)     # Jester
vehicle_component_defs=rf_a_u;      2;  150;    1088;$(component_group_name_roof);$(name_alien)     # Uranus
vehicle_component_defs=rf_c_u;      2;  100;    1091;$(component_group_name_roof);$(name_xflow)     # Uranus
vehicle_component_defs=rf_lr_bl2;   2;  3250;   1103;$(component_group_name_roof);Складывающаяся    # Blade
vehicle_component_defs=rf_lr_bl1;   2;  3340;   1128;$(component_group_name_roof);Выниловая         # Blade
vehicle_component_defs=rf_lr_sv1;   2;  3380;   1130;$(component_group_name_roof);Жесткая           # Savanna
vehicle_component_defs=rf_lr_sv2;   2;  3290;   1131;$(component_group_name_roof);Мягкая            # Savanna

# Боковые обтекатели идут парами. Название берется только левого (как в файле carmods.dat)
vehicle_component_defs=wg_l_b_ssk;  3;  500;    1007,1017;$(component_group_name_sideskirt);Обтекатель
vehicle_component_defs=wg_l_a_s;    3;  480;    1026,1027;$(component_group_name_sideskirt);$(name_alien)   # Sultan
vehicle_component_defs=wg_l_c_s;    3;  370;    1031,1030;$(component_group_name_sideskirt);$(name_xflow)   # Sultan
vehicle_component_defs=wg_l_a_l;    3;  500;    1036,1040;$(component_group_name_sideskirt);$(name_alien)   # Elegy
vehicle_component_defs=wg_l_c_l;    3;  390;    1039,1041;$(component_group_name_sideskirt);$(name_xflow)   # Elegy
vehicle_component_defs=wg_l_lr_br1; 3;  1000;   1042,1099;$(component_group_name_sideskirt);$(name_chrome)  # Broadway
vehicle_component_defs=wg_l_a_f;    3;  670;    1047,1051;$(component_group_name_sideskirt);$(name_alien)   # Flash
vehicle_component_defs=wg_l_c_f;    3;  530;    1048,1052;$(component_group_name_sideskirt);$(name_xflow)   # Flash
vehicle_component_defs=wg_l_a_st;   3;  520;    1056,1062;$(component_group_name_sideskirt);$(name_alien)   # Statum
vehicle_component_defs=wg_l_c_st;   3;  430;    1057,1063;$(component_group_name_sideskirt);$(name_xflow)   # Statum
vehicle_component_defs=wg_l_a_j;    3;  550;    1069,1071;$(component_group_name_sideskirt);$(name_alien)   # Jester
vehicle_component_defs=wg_l_c_j;    3;  450;    1070,1072;$(component_group_name_sideskirt);$(name_xflow)   # Jester
vehicle_component_defs=wg_l_a_u;    3;  450;    1090,1094;$(component_group_name_sideskirt);$(name_alien)   # Uranus
vehicle_component_defs=wg_l_c_u;    3;  350;    1093,1095;$(component_group_name_sideskirt);$(name_xflow)   # Uranus
vehicle_component_defs=wg_l_lr_rem1;3;  780;    1122,1101;$(component_group_name_sideskirt);Огонь           # Remington
vehicle_component_defs=wg_l_lr_rem2;3;  780;    1106,1124;$(component_group_name_sideskirt);Изгиб           # Remington
vehicle_component_defs=wg_l_lr_sv;  3;  830;    1133,1102;$(component_group_name_sideskirt);Полоска         # Savanna
vehicle_component_defs=wg_l_lr_bl1; 3;  780;    1108,1107;$(component_group_name_sideskirt);Полоска         # Blade
vehicle_component_defs=wg_l_lr_slv1;3;  780;    1118,1120;$(component_group_name_sideskirt);$(name_chrome)  # Slamvan
vehicle_component_defs=wg_l_lr_slv2;3;  940;    1119,1121;$(component_group_name_sideskirt);Колпаки         # Slamvan
vehicle_component_defs=wg_l_lr_t1;  3;  800;    1134,1137;$(component_group_name_sideskirt);Полоска         # Tornado

vehicle_component_defs=lgt_b_rspt;  4;  100;    1013;$(component_group_name_lamps);Круглые
vehicle_component_defs=lgt_b_sspt;  4;  50;     1024;$(component_group_name_lamps);Квадратные

vehicle_component_defs=nto_b_s;     5;  200;    1009;$(component_group_name_nitro);02 раза
vehicle_component_defs=nto_b_l;     5;  500;    1008;$(component_group_name_nitro);05 раза
vehicle_component_defs=nto_b_tw;    5;  1000;   1010;$(component_group_name_nitro);10 раз
# Азот может исчезать из машины - поэтому мы не проверяем его на дубликат
vehicle_component_ignore_duplicate=nto_b_s
vehicle_component_ignore_duplicate=nto_b_l
vehicle_component_ignore_duplicate=nto_b_tw

vehicle_component_defs=exh_b_ts;    6;  350;    1018;$(component_group_name_exhaust);Острие
vehicle_component_defs=exh_b_t;     6;  300;    1019;$(component_group_name_exhaust);Двойная
vehicle_component_defs=exh_b_l;     6;  250;    1020;$(component_group_name_exhaust);Большая
vehicle_component_defs=exh_b_m;     6;  200;    1021;$(component_group_name_exhaust);Средняя
vehicle_component_defs=exh_b_s;     6;  150;    1022;$(component_group_name_exhaust);Маленькая
vehicle_component_defs=exh_a_s;     6;  770;    1028;$(component_group_name_exhaust);$(name_alien)      # Sultan
vehicle_component_defs=exh_c_s;     6;  680;    1029;$(component_group_name_exhaust);$(name_xflow)      # Sultan
vehicle_component_defs=exh_a_l;     6;  790;    1034;$(component_group_name_exhaust);$(name_alien)      # Elegy
vehicle_component_defs=exh_c_l;     6;  690;    1037;$(component_group_name_exhaust);$(name_xflow)      # Elegy
vehicle_component_defs=exh_lr_br1;  6;  500;    1044;$(component_group_name_exhaust);$(name_chrome)     # Broadway
vehicle_component_defs=exh_lr_br2;  6;  500;    1043;$(component_group_name_exhaust);$(name_slamin)     # Broadway
vehicle_component_defs=exh_c_f;     6;  510;    1045;$(component_group_name_exhaust);$(name_xflow)      # Flash
vehicle_component_defs=exh_a_f;     6;  710;    1046;$(component_group_name_exhaust);$(name_alien)      # Flash
vehicle_component_defs=exh_c_st;    6;  720;    1059;$(component_group_name_exhaust);$(name_xflow)      # Statum
vehicle_component_defs=exh_a_st;    6;  830;    1064;$(component_group_name_exhaust);$(name_alien)      # Statum
vehicle_component_defs=exh_a_j;     6;  850;    1065;$(component_group_name_exhaust);$(name_alien)      # Jester
vehicle_component_defs=exh_c_j;     6;  750;    1066;$(component_group_name_exhaust);$(name_xflow)      # Jester
vehicle_component_defs=exh_c_u;     6;  650;    1089;$(component_group_name_exhaust);$(name_xflow)      # Uranus
vehicle_component_defs=exh_a_u;     6;  750;    1092;$(component_group_name_exhaust);$(name_alien)      # Uranus
vehicle_component_defs=exh_lr_bl1;  6;  1610;   1104;$(component_group_name_exhaust);$(name_chrome)     # Blade
vehicle_component_defs=exh_lr_bl2;  6;  1540;   1105;$(component_group_name_exhaust);$(name_slamin)     # Blade
vehicle_component_defs=exh_lr_slv1; 6;  3340;   1113;$(component_group_name_exhaust);$(name_chrome)     # Slamvan
vehicle_component_defs=exh_lr_slv2; 6;  3250;   1114;$(component_group_name_exhaust);$(name_slamin)     # Slamvan
vehicle_component_defs=exh_lr_rem1; 6;  3340;   1126;$(component_group_name_exhaust);$(name_chrome)     # Remington
vehicle_component_defs=exh_lr_rem2; 6;  3250;   1127;$(component_group_name_exhaust);$(name_slamin)     # Remington
vehicle_component_defs=exh_lr_sv1;  6;  1650;   1129;$(component_group_name_exhaust);$(name_chrome)     # Savanna
vehicle_component_defs=exh_lr_sv2;  6;  1590;   1132;$(component_group_name_exhaust);$(name_slamin)     # Savanna
vehicle_component_defs=exh_lr_t2;   6;  1500;   1135;$(component_group_name_exhaust);$(name_slamin)     # Tornado
vehicle_component_defs=exh_lr_t1;   6;  1000;   1136;$(component_group_name_exhaust);$(name_chrome)     # Tornado

vehicle_component_defs=wheel_gn1;   7;  820;    1082;$(component_group_name_wheels);Импорт
vehicle_component_defs=wheel_gn2;   7;  770;    1085;$(component_group_name_wheels);Элементарные
vehicle_component_defs=wheel_gn3;   7;  1000;   1096;$(component_group_name_wheels);Ахаб
vehicle_component_defs=wheel_gn4;   7;  620;    1097;$(component_group_name_wheels);Мнимые
vehicle_component_defs=wheel_gn5;   7;  1140;   1098;$(component_group_name_wheels);Доступные
vehicle_component_defs=wheel_lr1;   7;  1620;   1077;$(component_group_name_wheels);Классика
vehicle_component_defs=wheel_lr2;   7;  1560;   1083;$(component_group_name_wheels);Доллар
vehicle_component_defs=wheel_lr3;   7;  1200;   1078;$(component_group_name_wheels);Крученные
vehicle_component_defs=wheel_lr4;   7;  1560;   1076;$(component_group_name_wheels);Спицевые
vehicle_component_defs=wheel_lr5;   7;  1350;   1084;$(component_group_name_wheels);Транс
vehicle_component_defs=wheel_or1;   7;  1000;   1025;$(component_group_name_wheels);Внедорожные
vehicle_component_defs=wheel_sr1;   7;  1030;   1079;$(component_group_name_wheels);Резные
vehicle_component_defs=wheel_sr2;   7;  980;    1075;$(component_group_name_wheels);Солнышко
vehicle_component_defs=wheel_sr3;   7;  1030;   1074;$(component_group_name_wheels);Мега
vehicle_component_defs=wheel_sr4;   7;  1230;   1081;$(component_group_name_wheels);Роща
vehicle_component_defs=wheel_sr5;   7;  900;    1080;$(component_group_name_wheels);Прутковые
vehicle_component_defs=wheel_sr6;   7;  1100;   1073;$(component_group_name_wheels);Тень

vehicle_component_defs=stereo;      8;  100;    1086;$(component_group_name_stereo);Стерео

vehicle_component_defs=hydralics;   9;  1500;   1087;$(component_group_name_hydraulics);Гидравлика

vehicle_component_defs=fbmp_lr_slv1;10; 2040;   1117;$(component_group_name_front_bumper);$(name_chrome)    # Slamvan
vehicle_component_defs=fbmp_c_f;    10; 910;    1152;$(component_group_name_front_bumper);$(name_xflow)     # Flash
vehicle_component_defs=fbmp_a_f;    10; 1200;   1153;$(component_group_name_front_bumper);$(name_alien)     # Flash
vehicle_component_defs=fbmp_a_st;   10; 1030;   1155;$(component_group_name_front_bumper);$(name_alien)     # Stratum
vehicle_component_defs=fbmp_c_st;   10; 930;    1157;$(component_group_name_front_bumper);$(name_xflow)     # Stratum
vehicle_component_defs=fbmp_a_j;    10; 1050;   1160;$(component_group_name_front_bumper);$(name_alien)     # Jester
vehicle_component_defs=fbmp_c_j;    10; 950;    1173;$(component_group_name_front_bumper);$(name_xflow)     # Jester
vehicle_component_defs=fbmp_c_u;    10; 850;    1165;$(component_group_name_front_bumper);$(name_xflow)     # Uranus
vehicle_component_defs=fbmp_a_u;    10; 950;    1166;$(component_group_name_front_bumper);$(name_alien)     # Uranus
vehicle_component_defs=fbmp_a_s;    10; 970;    1169;$(component_group_name_front_bumper);$(name_alien)     # Sultan
vehicle_component_defs=fbmp_c_s;    10; 880;    1170;$(component_group_name_front_bumper);$(name_xflow)     # Sultan
vehicle_component_defs=fbmp_a_l;    10; 990;    1171;$(component_group_name_front_bumper);$(name_alien)     # Elegy
vehicle_component_defs=fbmp_c_l;    10; 900;    1172;$(component_group_name_front_bumper);$(name_xflow)     # Elegy
vehicle_component_defs=fbmp_lr_br1; 10; 1000;   1174;$(component_group_name_front_bumper);$(name_chrome)    # Broadway
vehicle_component_defs=fbmp_lr_br2; 10; 900;    1175;$(component_group_name_front_bumper);$(name_slamin)    # Broadway
vehicle_component_defs=fbmp_lr_rem1;10; 2150;   1179;$(component_group_name_front_bumper);$(name_chrome)    # Remington
vehicle_component_defs=fbmp_lr_rem2;10; 2040;   1185;$(component_group_name_front_bumper);$(name_slamin)    # Remington
vehicle_component_defs=fbmp_lr_bl2; 10; 2050;   1181;$(component_group_name_front_bumper);$(name_slamin)    # Blade
vehicle_component_defs=fbmp_lr_bl1; 10; 2130;   1182;$(component_group_name_front_bumper);$(name_chrome)    # Blade
vehicle_component_defs=fbmp_lr_sv2; 10; 2080;   1188;$(component_group_name_front_bumper);$(name_slamin)    # Savanna
vehicle_component_defs=fbmp_lr_sv1; 10; 2200;   1189;$(component_group_name_front_bumper);$(name_chrome)    # Savanna
vehicle_component_defs=fbmp_lr_t2;  10; 1200;   1190;$(component_group_name_front_bumper);$(name_slamin)    # Tornado
vehicle_component_defs=fbmp_lr_t1;  10; 1040;   1191;$(component_group_name_front_bumper);$(name_chrome)    # Tornado

vehicle_component_defs=rbmp_c_s;    11; 870;    1140;$(component_group_name_rear_bumper);$(name_xflow)      # Sultan
vehicle_component_defs=rbmp_a_s;    11; 980;    1141;$(component_group_name_rear_bumper);$(name_alien)      # Sultan
vehicle_component_defs=rbmp_c_l;    11; 890;    1148;$(component_group_name_rear_bumper);$(name_xflow)      # Elegy
vehicle_component_defs=rbmp_a_l;    11; 1000;   1149;$(component_group_name_rear_bumper);$(name_alien)      # Elegy
vehicle_component_defs=rbmp_a_f;    11; 1090;   1150;$(component_group_name_rear_bumper);$(name_alien)      # Flash
vehicle_component_defs=rbmp_c_f;    11; 840;    1151;$(component_group_name_rear_bumper);$(name_xflow)      # Flash
vehicle_component_defs=rbmp_a_st;   11; 1030;   1154;$(component_group_name_rear_bumper);$(name_alien)      # Stratum
vehicle_component_defs=rbmp_c_st;   11; 920;    1156;$(component_group_name_rear_bumper);$(name_xflow)      # Stratum
vehicle_component_defs=rbmp_a_j;    11; 1050;   1159;$(component_group_name_rear_bumper);$(name_alien)      # Jester
vehicle_component_defs=rbmp_c_j;    11; 950;    1161;$(component_group_name_rear_bumper);$(name_xflow)      # Jester
vehicle_component_defs=rbmp_c_u;    11; 850;    1167;$(component_group_name_rear_bumper);$(name_xflow)      # Uranus
vehicle_component_defs=rbmp_a_u;    11; 950;    1168;$(component_group_name_rear_bumper);$(name_alien)      # Uranus
vehicle_component_defs=rbmp_lr_br1; 11; 1000;   1176;$(component_group_name_rear_bumper);$(name_chrome)     # Broadway
vehicle_component_defs=rbmp_lr_br2; 11; 900;    1177;$(component_group_name_rear_bumper);$(name_slamin)     # Broadway
vehicle_component_defs=rbmp_lr_rem2;11; 2050;   1178;$(component_group_name_rear_bumper);$(name_slamin)     # Remington
vehicle_component_defs=rbmp_lr_rem1;11; 2130;   1180;$(component_group_name_rear_bumper);$(name_chrome)     # Remington
vehicle_component_defs=rbmp_lr_bl2; 11; 2040;   1183;$(component_group_name_rear_bumper);$(name_slamin)     # Blade
vehicle_component_defs=rbmp_lr_bl1; 11; 2150;   1184;$(component_group_name_rear_bumper);$(name_chrome)     # Blade
vehicle_component_defs=rbmp_lr_sv2; 11; 2095;   1186;$(component_group_name_rear_bumper);$(name_slamin)     # Savanna
vehicle_component_defs=rbmp_lr_sv1; 11; 2175;   1187;$(component_group_name_rear_bumper);$(name_chrome)     # Savanna
vehicle_component_defs=rbmp_lr_t1;  11; 940;    1192;$(component_group_name_rear_bumper);$(name_chrome)     # Tornado
vehicle_component_defs=rbmp_lr_t2;  11; 1100;   1193;$(component_group_name_rear_bumper);$(name_slamin)     # Tornado

# тоже парами
vehicle_component_defs=bntl_b_ov;   12; 150;    1143,1142;$(component_group_name_vents);Овальная
vehicle_component_defs=bntl_b_sq;   12; 100;    1145,1144;$(component_group_name_vents);Квадратная

# Может быть тоже что и component_group_name_front_bumper
vehicle_component_defs=misc_c_lr_rem1;  13; 940;  1100;$(component_group_name_bullbars);ограждение    # Remington
vehicle_component_defs=misc_c_lr_rem2;  13; 860;  1123;$(component_group_name_bullbars);решетка       # Remington
vehicle_component_defs=misc_c_lr_rem3;  13; 1120; 1125;$(component_group_name_bullbars);свет          # Remington

# Может быть тоже что и component_group_name_front_bumper
vehicle_component_defs=fbb_lr_slv1; 14; 2130;   1115;$(component_group_name_front_bullbars);$(name_chrome)  # Slamvan
vehicle_component_defs=fbb_lr_slv2; 14; 2050;   1116;$(component_group_name_front_bullbars);$(name_slamin)  # Slamvan

# Может быть тоже что и component_group_name_rear_bumper
vehicle_component_defs=bbb_lr_slv1; 15; 1610;   1109;$(component_group_name_rear_bullbars);$(name_chrome)   # Slamvan
vehicle_component_defs=bbb_lr_slv2; 15; 1540;   1110;$(component_group_name_rear_bullbars);$(name_slamin)   # Slamvan
