#include "config.hpp"
#include "geo_info_getter_localization.hpp"
#include "../geo_ip_info.hpp"

namespace geo {
    info_getter_localization::info_getter_localization() {
        countries_ru.insert(std::make_pair("AU", "Австралия"));
        countries_ru.insert(std::make_pair("AT", "Австрия"));
        countries_ru.insert(std::make_pair("AZ", "Азербайджан"));
        countries_ru.insert(std::make_pair("AX", "Аландские острова"));
        countries_ru.insert(std::make_pair("AL", "Албания"));
        countries_ru.insert(std::make_pair("DZ", "Алжир"));
        countries_ru.insert(std::make_pair("UM", "Внешние малые острова (США)"));
        countries_ru.insert(std::make_pair("VI", "Американские Виргинские острова"));
        countries_ru.insert(std::make_pair("AS", "Американское Самоа"));
        countries_ru.insert(std::make_pair("AI", "Ангилья"));
        countries_ru.insert(std::make_pair("AO", "Ангола"));
        countries_ru.insert(std::make_pair("AD", "Андорра"));
        countries_ru.insert(std::make_pair("AQ", "Антарктида"));
        countries_ru.insert(std::make_pair("AG", "Антигуа и Барбуда"));
        countries_ru.insert(std::make_pair("AR", "Аргентина"));
        countries_ru.insert(std::make_pair("AM", "Армения"));
        countries_ru.insert(std::make_pair("AW", "Аруба"));
        countries_ru.insert(std::make_pair("AF", "Афганистан"));
        countries_ru.insert(std::make_pair("BS", "Багамские острова"));
        countries_ru.insert(std::make_pair("BD", "Бангладеш"));
        countries_ru.insert(std::make_pair("BB", "Барбадос"));
        countries_ru.insert(std::make_pair("BH", "Бахрейн"));
        countries_ru.insert(std::make_pair("BZ", "Белиз"));
        countries_ru.insert(std::make_pair("BY", "Белоруссия"));
        countries_ru.insert(std::make_pair("BE", "Бельгия"));
        countries_ru.insert(std::make_pair("BJ", "Бенин"));
        countries_ru.insert(std::make_pair("BM", "Бермуды"));
        countries_ru.insert(std::make_pair("BG", "Болгария"));
        countries_ru.insert(std::make_pair("BO", "Боливия"));
        countries_ru.insert(std::make_pair("BA", "Босния и Герцеговина"));
        countries_ru.insert(std::make_pair("BW", "Ботсвана"));
        countries_ru.insert(std::make_pair("BR", "Бразилия"));
        countries_ru.insert(std::make_pair("IO", "Британские территории в Индийском океане"));
        countries_ru.insert(std::make_pair("VG", "Британские Виргинские острова"));
        countries_ru.insert(std::make_pair("BN", "Бруней"));
        countries_ru.insert(std::make_pair("BF", "Буркина Фасо"));
        countries_ru.insert(std::make_pair("BI", "Бурунди"));
        countries_ru.insert(std::make_pair("BT", "Бутан"));
        countries_ru.insert(std::make_pair("VU", "Вануату"));
        countries_ru.insert(std::make_pair("VA", "Ватикан"));
        countries_ru.insert(std::make_pair("GB", "Великобритания"));
        countries_ru.insert(std::make_pair("HU", "Венгрия"));
        countries_ru.insert(std::make_pair("VE", "Венесуэла"));
        countries_ru.insert(std::make_pair("TL", "Восточный Тимор"));
        countries_ru.insert(std::make_pair("VN", "Вьетнам"));
        countries_ru.insert(std::make_pair("GA", "Габон"));
        countries_ru.insert(std::make_pair("HT", "Гаити"));
        countries_ru.insert(std::make_pair("GY", "Гайана"));
        countries_ru.insert(std::make_pair("GM", "Гамбия"));
        countries_ru.insert(std::make_pair("GH", "Гана"));
        countries_ru.insert(std::make_pair("GP", "Гваделупа"));
        countries_ru.insert(std::make_pair("GT", "Гватемала"));
        countries_ru.insert(std::make_pair("GN", "Гвинея"));
        countries_ru.insert(std::make_pair("GW", "Гвинея-Бисау"));
        countries_ru.insert(std::make_pair("DE", "Германия"));
        countries_ru.insert(std::make_pair("GI", "Гибралтар"));
        countries_ru.insert(std::make_pair("HN", "Гондурас"));
        countries_ru.insert(std::make_pair("HK", "Гонконг"));
        countries_ru.insert(std::make_pair("GD", "Гренада"));
        countries_ru.insert(std::make_pair("GL", "Гренландия"));
        countries_ru.insert(std::make_pair("GR", "Греция"));
        countries_ru.insert(std::make_pair("GE", "Грузия"));
        countries_ru.insert(std::make_pair("GU", "Гуам"));
        countries_ru.insert(std::make_pair("DK", "Дания"));
        countries_ru.insert(std::make_pair("CD", "ДР Конго"));
        countries_ru.insert(std::make_pair("DJ", "Джибути"));
        countries_ru.insert(std::make_pair("DM", "Доминика"));
        countries_ru.insert(std::make_pair("DO", "Доминиканская Республика"));
        countries_ru.insert(std::make_pair("EU", "Европейский Союз"));
        countries_ru.insert(std::make_pair("EG", "Египет"));
        countries_ru.insert(std::make_pair("ZM", "Замбия"));
        countries_ru.insert(std::make_pair("EH", "Западная Сахара"));
        countries_ru.insert(std::make_pair("ZW", "Зимбабве"));
        countries_ru.insert(std::make_pair("IL", "Израиль"));
        countries_ru.insert(std::make_pair("IN", "Индия"));
        countries_ru.insert(std::make_pair("ID", "Индонезия"));
        countries_ru.insert(std::make_pair("JO", "Иордания"));
        countries_ru.insert(std::make_pair("IQ", "Ирак"));
        countries_ru.insert(std::make_pair("IR", "Иран"));
        countries_ru.insert(std::make_pair("IE", "Ирландия"));
        countries_ru.insert(std::make_pair("IS", "Исландия"));
        countries_ru.insert(std::make_pair("ES", "Испания"));
        countries_ru.insert(std::make_pair("IT", "Италия"));
        countries_ru.insert(std::make_pair("YE", "Йемен"));
        countries_ru.insert(std::make_pair("KP", "КНДР"));
        countries_ru.insert(std::make_pair("CV", "Кабо-Верде"));
        countries_ru.insert(std::make_pair("KZ", "Казахстан"));
        countries_ru.insert(std::make_pair("KY", "Каймановы острова"));
        countries_ru.insert(std::make_pair("KH", "Камбоджа"));
        countries_ru.insert(std::make_pair("CM", "Камерун"));
        countries_ru.insert(std::make_pair("CA", "Канада"));
        countries_ru.insert(std::make_pair("QA", "Катар"));
        countries_ru.insert(std::make_pair("KE", "Кения"));
        countries_ru.insert(std::make_pair("CY", "Кипр"));
        countries_ru.insert(std::make_pair("KG", "Киргизия"));
        countries_ru.insert(std::make_pair("KI", "Кирибати"));
        countries_ru.insert(std::make_pair("CN", "Китай"));
        countries_ru.insert(std::make_pair("CC", "Кокосовые острова"));
        countries_ru.insert(std::make_pair("CO", "Колумбия"));
        countries_ru.insert(std::make_pair("KM", "Коморские острова"));
        countries_ru.insert(std::make_pair("CR", "Коста-Рика"));
        countries_ru.insert(std::make_pair("CI", "Кот-д’Ивуар"));
        countries_ru.insert(std::make_pair("CU", "Куба"));
        countries_ru.insert(std::make_pair("KW", "Кувейт"));
        countries_ru.insert(std::make_pair("LA", "Лаос"));
        countries_ru.insert(std::make_pair("LV", "Латвия"));
        countries_ru.insert(std::make_pair("LS", "Лесото"));
        countries_ru.insert(std::make_pair("LR", "Либерия"));
        countries_ru.insert(std::make_pair("LB", "Ливан"));
        countries_ru.insert(std::make_pair("LY", "Ливия"));
        countries_ru.insert(std::make_pair("LT", "Литва"));
        countries_ru.insert(std::make_pair("LI", "Лихтенштейн"));
        countries_ru.insert(std::make_pair("LU", "Люксембург"));
        countries_ru.insert(std::make_pair("MU", "Маврикий"));
        countries_ru.insert(std::make_pair("MR", "Мавритания"));
        countries_ru.insert(std::make_pair("MG", "Мадагаскар"));
        countries_ru.insert(std::make_pair("YT", "Майотта"));
        countries_ru.insert(std::make_pair("MO", "Макао"));
        countries_ru.insert(std::make_pair("MK", "Македония"));
        countries_ru.insert(std::make_pair("MW", "Малави"));
        countries_ru.insert(std::make_pair("MY", "Малайзия"));
        countries_ru.insert(std::make_pair("ML", "Мали"));
        countries_ru.insert(std::make_pair("MV", "Мальдивы"));
        countries_ru.insert(std::make_pair("MT", "Мальта"));
        countries_ru.insert(std::make_pair("MA", "Марокко"));
        countries_ru.insert(std::make_pair("MQ", "Мартиника"));
        countries_ru.insert(std::make_pair("MH", "Маршалловы острова"));
        countries_ru.insert(std::make_pair("MX", "Мексика"));
        countries_ru.insert(std::make_pair("MZ", "Мозамбик"));
        countries_ru.insert(std::make_pair("MD", "Молдавия"));
        countries_ru.insert(std::make_pair("MC", "Монако"));
        countries_ru.insert(std::make_pair("MN", "Монголия"));
        countries_ru.insert(std::make_pair("MS", "Монтсеррат"));
        countries_ru.insert(std::make_pair("MM", "Мьянма"));
        countries_ru.insert(std::make_pair("NA", "Намибия"));
        countries_ru.insert(std::make_pair("NR", "Науру"));
        countries_ru.insert(std::make_pair("NP", "Непал"));
        countries_ru.insert(std::make_pair("NE", "Нигер"));
        countries_ru.insert(std::make_pair("NG", "Нигерия"));
        countries_ru.insert(std::make_pair("AN", "Нидерландские Антильские острова"));
        countries_ru.insert(std::make_pair("NL", "Нидерланды"));
        countries_ru.insert(std::make_pair("NI", "Никарагуа"));
        countries_ru.insert(std::make_pair("NU", "Ниуэ"));
        countries_ru.insert(std::make_pair("NC", "Новая Каледония"));
        countries_ru.insert(std::make_pair("NZ", "Новая Зеландия"));
        countries_ru.insert(std::make_pair("NO", "Норвегия"));
        countries_ru.insert(std::make_pair("AE", "ОАЭ"));
        countries_ru.insert(std::make_pair("OM", "Оман"));
        countries_ru.insert(std::make_pair("CX", "Остров Рождества"));
        countries_ru.insert(std::make_pair("CK", "Острова Кука"));
        countries_ru.insert(std::make_pair("HM", "Херд и Макдональд"));
        countries_ru.insert(std::make_pair("PK", "Пакистан"));
        countries_ru.insert(std::make_pair("PW", "Палау"));
        countries_ru.insert(std::make_pair("PS", "Палестина"));
        countries_ru.insert(std::make_pair("PA", "Панама"));
        countries_ru.insert(std::make_pair("PG", "Папуа — Новая Гвинея"));
        countries_ru.insert(std::make_pair("PY", "Парагвай"));
        countries_ru.insert(std::make_pair("PE", "Перу"));
        countries_ru.insert(std::make_pair("PN", "Питкэрн"));
        countries_ru.insert(std::make_pair("PL", "Польша"));
        countries_ru.insert(std::make_pair("PT", "Португалия"));
        countries_ru.insert(std::make_pair("PR", "Пуэрто-Рико"));
        countries_ru.insert(std::make_pair("CG", "Республика Конго"));
        countries_ru.insert(std::make_pair("RE", "Реюньон"));
        countries_ru.insert(std::make_pair("RU", "Россия"));
        countries_ru.insert(std::make_pair("RW", "Руанда"));
        countries_ru.insert(std::make_pair("RO", "Румыния"));
        countries_ru.insert(std::make_pair("US", "США"));
        countries_ru.insert(std::make_pair("SV", "Сальвадор"));
        countries_ru.insert(std::make_pair("WS", "Самоа"));
        countries_ru.insert(std::make_pair("SM", "Сан-Марино"));
        countries_ru.insert(std::make_pair("ST", "Сан-Томе и Принсипи"));
        countries_ru.insert(std::make_pair("SA", "Саудовская Аравия"));
        countries_ru.insert(std::make_pair("SZ", "Свазиленд"));
        countries_ru.insert(std::make_pair("SJ", "Шпицберген и Ян-Майен"));
        countries_ru.insert(std::make_pair("MP", "Северные Марианские острова"));
        countries_ru.insert(std::make_pair("SC", "Сейшельские острова"));
        countries_ru.insert(std::make_pair("SN", "Сенегал"));
        countries_ru.insert(std::make_pair("VC", "Сент-Винсент и Гренадины"));
        countries_ru.insert(std::make_pair("KN", "Сент-Китс и Невис"));
        countries_ru.insert(std::make_pair("LC", "Сент-Люсия"));
        countries_ru.insert(std::make_pair("PM", "Сен-Пьер и Микелон"));
        countries_ru.insert(std::make_pair("RS", "Сербия"));
        countries_ru.insert(std::make_pair("CS", "Сербия и Черногория"));
        countries_ru.insert(std::make_pair("SG", "Сингапур"));
        countries_ru.insert(std::make_pair("SY", "Сирия"));
        countries_ru.insert(std::make_pair("SK", "Словакия"));
        countries_ru.insert(std::make_pair("SI", "Словения"));
        countries_ru.insert(std::make_pair("SB", "Соломоновы острова"));
        countries_ru.insert(std::make_pair("SO", "Сомали"));
        countries_ru.insert(std::make_pair("SD", "Судан"));
        countries_ru.insert(std::make_pair("SR", "Суринам"));
        countries_ru.insert(std::make_pair("SL", "Сьерра-Леоне"));
        countries_ru.insert(std::make_pair("SU", "СССР"));
        countries_ru.insert(std::make_pair("TJ", "Таджикистан"));
        countries_ru.insert(std::make_pair("TH", "Таиланд"));
        countries_ru.insert(std::make_pair("TW", "Тайвань"));
        countries_ru.insert(std::make_pair("TZ", "Танзания"));
        countries_ru.insert(std::make_pair("TG", "Того"));
        countries_ru.insert(std::make_pair("TK", "Токелау"));
        countries_ru.insert(std::make_pair("TO", "Тонга"));
        countries_ru.insert(std::make_pair("TT", "Тринидад и Тобаго"));
        countries_ru.insert(std::make_pair("TV", "Тувалу"));
        countries_ru.insert(std::make_pair("TN", "Тунис"));
        countries_ru.insert(std::make_pair("TM", "Туркмения"));
        countries_ru.insert(std::make_pair("TR", "Турция"));
        countries_ru.insert(std::make_pair("UG", "Уганда"));
        countries_ru.insert(std::make_pair("UZ", "Узбекистан"));
        countries_ru.insert(std::make_pair("UA", "Украина"));
        countries_ru.insert(std::make_pair("UY", "Уругвай"));
        countries_ru.insert(std::make_pair("FO", "Фарерские острова"));
        countries_ru.insert(std::make_pair("FM", "Федеративные Штаты Микронезии"));
        countries_ru.insert(std::make_pair("FJ", "Фиджи"));
        countries_ru.insert(std::make_pair("PH", "Филиппины"));
        countries_ru.insert(std::make_pair("FI", "Финляндия"));
        countries_ru.insert(std::make_pair("FK", "Фолклендские острова"));
        countries_ru.insert(std::make_pair("FR", "Франция"));
        countries_ru.insert(std::make_pair("GF", "Французская Гвиана"));
        countries_ru.insert(std::make_pair("PF", "Французская Полинезия"));
        countries_ru.insert(std::make_pair("TF", "Французские Южные и Антарктические Территории"));
        countries_ru.insert(std::make_pair("HR", "Хорватия"));
        countries_ru.insert(std::make_pair("CF", "ЦАР"));
        countries_ru.insert(std::make_pair("TD", "Чад"));
        countries_ru.insert(std::make_pair("ME", "Черногория"));
        countries_ru.insert(std::make_pair("CZ", "Чехия"));
        countries_ru.insert(std::make_pair("CL", "Чили"));
        countries_ru.insert(std::make_pair("CH", "Швейцария"));
        countries_ru.insert(std::make_pair("SE", "Швеция"));
        countries_ru.insert(std::make_pair("LK", "Шри-Ланка"));
        countries_ru.insert(std::make_pair("EC", "Эквадор"));
        countries_ru.insert(std::make_pair("GQ", "Экваториальная Гвинея"));
        countries_ru.insert(std::make_pair("ER", "Эритрея"));
        countries_ru.insert(std::make_pair("EE", "Эстония"));
        countries_ru.insert(std::make_pair("ET", "Эфиопия"));
        countries_ru.insert(std::make_pair("ZA", "ЮАР"));
        countries_ru.insert(std::make_pair("KR", "Респ. Корея"));
        countries_ru.insert(std::make_pair("GS", "Южная Георгия и Южные Сандвичевы острова"));
        countries_ru.insert(std::make_pair("JM", "Ямайка"));
        countries_ru.insert(std::make_pair("JP", "Япония"));
        countries_ru.insert(std::make_pair("BV", "Остров Буве"));
        countries_ru.insert(std::make_pair("NF", "Норфолк"));
        countries_ru.insert(std::make_pair("SH", "О.Святой Елены"));
        countries_ru.insert(std::make_pair("TC", "Тёркс и Кайкос"));
        countries_ru.insert(std::make_pair("WF", "Уоллис и Футуна"));
    }

    info_getter_localization::~info_getter_localization() {
    }

    void info_getter_localization::process_ip_info(ip_info& info) {
        if (info.country_code2) {
            if (countries_ru.find(info.country_code2.get()) != countries_ru.end()) {
                info.country_name_ru.reset(countries_ru[info.country_code2.get()]);
            }
        }
    }

    bool info_getter_localization::get_db_info(std::string& db_info_string) const {
        return false;
    }
} // namespace geo {
